MarketService.Web.FrontEnd/Models/Dtos/ResultDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Market.AService.UI.Models.Dtos
{
    public class ResultDto
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }

    public class ResultDto<T>
    {
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
        public T Data { get; set; }

    }

}

MarketService.Web.FrontEnd/Models/ErrorViewModel.cs
using System;

namespace Market.AService.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MarketService.Web.FrontEnd/Controllers/HomeController.cs
using MarketService.Web.FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MarketService.Web.FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarketService.Web.FrontEnd/Controllers/Mvc/BasketController.cs
using Market.AService.UI.Models.Dtos;
using Market.AService.UI.RestSharpServices.BasketSercvices;
using Market.AService.UI.RestSharpServices.BasketSercvices.Dtos;
using Market.AService.UI.RestSharpServices.DiscontServices;
using MarketService.Web.FrontEnd.Services.ProductServices;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Market.AService.UI.Controllers.Mvc
{
    public class BasketController : Controller
	{
		private readonly IBasketService basketService;
		private readonly IProductService productService;
        private readonly IDiscountService discountService;
        private readonly string UserId = "1";
		public BasketController(IBasketService basketService, IProductService productService, IDiscountService discountService)
		{
			this.basketService = basketService;
			this.productService = productService;
			this.discountService = discountService;
		}

        public IActionResult Index()
		{
			var basket = basketService.GetBasket(UserId);

            if (basket.discountId.HasValue)
            {
                var discount = discountService.GetDiscountById(basket.discountId.Value);
                basket.DiscountDetail = new DiscountInBasketDto
                {
                    Amount = discount.Data.Amount,
                    DiscountCode = discount.Data.Code,
                };
            }

            return View(basket);
		}

		public IActionResult Delete(Guid Id)
		{
			basketService.DeleteFromBasket(Id);
			return RedirectToAction("Index");
		}

		public IActionResult AddToBasket(Guid ProductId)
		{
			var product = productService.Getproduct(ProductId);
			var basket = basketService.GetBasket(UserId);

			AddToBasketDto item = new AddToBasketDto()
			{
				BasketId = basket.id,
				ImageUrl = product.image,
				ProductId = product.id,
				ProductName = product.name,
				Quantity = 1,
				UnitPrice = product.price,
			};
			basketService.AddToBasket(item, UserId);
			return RedirectToAction("Index");
		}

		public IActionResult Edit(Guid BasketItemId, int quantity)
		{
			basketService.UpdateQuantity(BasketItemId, quantity);
			return RedirectToAction("Index");

		}


        [Route("[controller]/ApplyDiscount")]
        public IActionResult ApplyDiscount(string DiscountCode)
        {
            if (string.IsNullOrWhiteSpace(DiscountCode))
            {
                return Json(new ResultDto
                {
                    IsSuccess = false,
                    Message = "لطفا کد تخفیف را وارد نمایید"
                });
            }
            var discount = discountService.GetDiscountByCode(DiscountCode);
            if (discount.IsSuccess == true)
            {
                if (discount.Data.Used)
                {
                    return Json(new ResultDto
                    {
                        IsSuccess = false,
                        Message = "این کد تخفیف قبلا استفاده شده است"
                    });
                }

                var basket = basketService.GetBasket(UserId);
                basketService.ApplyDiscountToBasket(Guid.Parse(basket.id), discount.Data.Id);
                discountService.UseDiscount(discount.Data.Id);
                return Json(new ResultDto
                {
                    IsSuccess = true,
                    Message = "کد تخفیف با موفقیت به سبد خرید شما اعمال شد",
                });
            }
            else
            {
                return Json(new ResultDto
                {
                    IsSuccess = false,
                    Message = discount.Message,
                });
            }
        }
    }
}

MarketService.Web.FrontEnd/Controllers/Mvc/HomeController.cs
using Market.AService.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MarketService.Web.FrontEnd.Controllers.Mvc
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MarketService.Web.FrontEnd/Controllers/Mvc/ProductController.cs
using MarketService.Web.FrontEnd.Services.ProductServices;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketService.Web.FrontEnd.Controllers.Mvc
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
                _productService = productService;
        }

        public IActionResult GetAll()
        {
             var rtn = _productService.GetAllProduct();
            return View(rtn);
        }
    }
}

MarketService.Web.FrontEnd/Views/Basket/Index.cshtml
@model Market.AService.UI.RestSharpServices.BasketSercvices.Dtos.BasketDto

@{
    ViewData["Title"] = "سبد خرید";
}
<h1>سبد خرید</h1>

<div class="row text-right">
    <table class="table col-md-9">
        <thead>
            <tr>

                <th>
                    <label asp-for="items.FirstOrDefault().productName"></label>
                </th>
                <th>
                    <label asp-for="items.FirstOrDefault().unitPrice"></label>
                </th>
                <th>
                    <label asp-for="items.FirstOrDefault().quantity"></label>
                </th>
                <th>
                    <label>قیمت کل</label>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.items)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.productName)
                    </td>
                    <td>
                        <b class="text-success">@item.unitPrice.ToString("n0")  تومان</b>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.quantity)
                    </td>
                    <td>
                        <b class="text-success">@item.TotalPrice().ToString("n0")  تومان</b>
                    </td>
                    <td class="row">
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Basket" asp-route-id="@item.id"> حذف</a>
                        <a class="btn btn-warning" onclick="ShowEdit('@item.id','@item.quantity')">ویزایش تعداد</a>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr class="bg-dark text-white">

                <td>
                    قیمت کل
                </td>
                <td>
                </td>
                <td>
                </td>
                <td>
                    <b>@Model.TotalPrice().ToString("n0")  تومان</b>
                </td>
                <td>
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="col-md-3 card">
        <div class="row col-md-12 card-body ">
            <label>استفاده از کد تخفیف</label>
            <input type="text" class="form-control col-md-12" id="txtDiscountCode" placeholder="کد تخفیف را وارد نمایید" />
            <button type="submit" onclick="ApplyDiscountCode()" id="btnApplyDiscountCode" class="btn btn-warning btn-sm col-md-12">اعمال کد تخفیف</button>


            <hr />
            @if (Model.DiscountDetail != null)
            {
                <div>
                    <b> کد تخفیف استفاده شده :</b>
                    <small>  @Model.DiscountDetail.DiscountCode</small>

                    <b class="col-md-12">مبلغ : @Model.DiscountDetail.Amount.ToString("n0")  تومان</b>
                </div>

            }

        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="editQuantityModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-action="Edit" asp-controller="Basket">
                <div class="modal-body">
                    <input type="hidden" id="BasketItemId" name="BasketItemId" value="" />
                    <input type="number" id="quantity" name="quantity" value="" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">برگشت</button>
                    <button type="submit" class="btn btn-primary">ثبت تغییرات</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>

        function ShowEdit(BasketItemId, quantity) {
            debugger;
            $("#BasketItemId").val(BasketItemId);
            $("#quantity").val(quantity);
            $("#editQuantityModal").modal({
                fadeDuration: 400,
                fadeDelay: 0.10
            });
        }
    </script>

    <script>
        function ApplyDiscountCode() {
            debugger;
            var code = $("#txtDiscountCode").val();

            var postData = { 'DiscountCode': code };

            $.ajax({
                contentType: 'application/x-www-form-urlencoded',
                dataType: 'json',
                type: "POST",
                url: "Basket/ApplyDiscount",
                data: postData,
                success: function (data) {
                    if (data.isSuccess) {
                        swal({
                            title: "بسیار خوب!",
                            text: data.message,
                            icon: "warning",
                            button: "خب",
                        });
                    }
                    else {
                        swal({
                            title: "هشدار!",
                            text: data.message,
                            icon: "warning",
                            button: "خب",
                        });
                    }
                }
            });
        }
    </script>

}

MarketService.Web.FrontEnd/Views/Product/GetAll.cshtml
@model IEnumerable<MarketService.Web.FrontEnd.Services.ProductServices.Dtos.ProductDto>

@{
    ViewData["Title"] = "GetAll";
}

<h1>GetAll</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @item.price.ToString("n0") تومان
                </td>
                <td>
                    <a asp-action="Details"
                       asp-controller="Product"
                       asp-route-id="@item.id">
                        جزئیات
                    </a>
                    <a asp-action="AddToBasket" asp-controller="Basket" asp-route-ProductId="@item.id" class="btn btn-success"> افزودن به سبد </a>

                </td>
            </tr>
        }
    </tbody>
</table>

MarketService.Web.FrontEnd/Views/Shared/DefaultPages/_SideBarPartial.cshtml
<!--sidebar wrapper -->
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">


        <a href="/">

            <img id="smallLgon" src="/panelcontent/logo/logo/Logo-eskenab.jpg" class="noneLogo" style="width:48px" alt="logo icon">
        </a>
        @*<div>
        <h4 style="font-size:12px !important; text-align:center" class="logo-text">سامانه مدیریت تسهيلات از محل وجوه اداره شده</h4>
        </div>*@
        <div class="toggle-icon ms-auto" onclick="toggleMenu()">
            <i class="bx bx-last-page"></i>
        </div>
        @*             <div class="toggle-icon ms-auto">
        <i class="bx @(((string)ViewBag.lang=="fa")?"bx-last-page":"bx-first-page")"></i>
        <i class="bx bx-last-page" ></i>
        </div>*@
    </div>

    <!--navigation-->
    <ul class="metismenu" id="menu">
        @if (User.Identity.IsAuthenticated)
        {

            @*  @if (userRoleName != null && userRoleName.Any(x => x.ToLower() == "admin"))
        {*@


            <li>
                <a class="has-arrow" href="javascript:;">
                    <div class="parent-icon">
                        <i class='bx bx-cog'></i>
                    </div>
                    <div class="menu-title">مدیریت</div>
                </a>

            </li>
        }
        <li>
            <a class="has-arrow" href="javascript:;">
                <div class="parent-icon">
                    <i class='bx bx-donate-heart'></i>
                </div>
                <div class="menu-title">محصولات</div>
            </a>
            <ul>
                <li>
                    <a href="/Basket/Index/">
                        <div class="parent-icon">
                            <i class="bx @(((string)ViewBag.lang=="fa")?"bx-left-arrow-alt":"bx-right-arrow-alt")  ">
                            </i>
                        </div>
                        <div class="menu-title">سبد خرید</div>
                    </a>
                </li>
                <li>
                    <a href="/Product/GetAll">
                        <div class="parent-icon">
                            <i class="bx @(((string)ViewBag.lang=="fa")?"bx-left-arrow-alt":"bx-right-arrow-alt")  "> </i>
                        </div>
                        <div class="menu-title">نمایش لیست محصولات</div>
                    </a>
                </li>

            </ul>
        </li>

        @*}*@
        @* else if (userRoleName != null && userRoleName.Any(x => x.ToLower() != "customer"))
        {
        <li>
        <a href="/home/index">
        <div class="parent-icon">
        <i class='lni lni-clipboard'></i>
        </div>
        <div class="menu-title">تعاونی</div>
        </a>
        </li>


        }
        else
        {
        @if (User.Identity.IsAuthenticated && userRoleName != null && userRoleName.Any(a => a.ToLower() == "customer"))
        {
        <li>
        <a href="/CompanyRegistration/">
        <div class="parent-icon">
        <i class='bx bx-building'></i>
        </div>
        <div class="menu-title"> تعاونی ها</div>
        </a>
        </li>
        }



        }*@

    </ul>
    <!--end navigation-->
</div>
<!--end sidebar wrapper -->